### ISSUE TITLE
Duplicate "attr" name issues when using multiple Android libraries

### ISSUE THREAD

**Issue by ashnehete** [davideas/FlipView#12]
Particularly the "animationDuration" attribute which already defined elsewhere.
Here's what I found in my research: https://code.google.com/p/android/issues/detail?id=22576
Suggested solution from the above link is to use app prefix.
<img width="879" alt="flipview-error-1" src="https://cloud.githubusercontent.com/assets/7398393/17644774/7c743c5e-61ad-11e6-9104-c54ee3653bb8.png">
<img width="698" alt="flipview-error-2" src="https://cloud.githubusercontent.com/assets/7398393/17644773/7c6b92d4-61ad-11e6-960e-7ca47a665089.png">

**Comment by davideas** [comment]
Hi @ashnehete, with which third library it goes in conflict?

**Comment by ashnehete** [comment]
https://github.com/HeinrichReimer/material-intro - This is the library I'm using.
https://github.com/Commit451/InkPageIndicator - I think this is the library which the above library uses which causes the conflict.

Additionally I also tried changing the build tools version from 23.0.3 to 24.0.1 and that worked.

**Comment by davideas** [comment]
Yes I confirm that Build tools v24.0.1 resolves the attributes conflict.
No need to add prefix anymore (to any library).

**Comment by ashnehete** [comment]
Yes that works too, sorry for the inconvenience. I had forked the library and added the prefixes. If anyone for any reason needs that. https://github.com/ashnehete/FlipView
