### ISSUE TITLE
Possibilty to remove a rear layout

### ISSUE THREAD

**Issue by sebschaef** [davideas/FlipView#20]
In FlipView, you can only "add" a rear layout. Meaning, that if you click on it, it shows in that order:
1. Predefined front layout
2. Predefined rear layout
3. Added rear layout

There's no way to remove the second or the third rear layout.

**Comment by davideas** [comment]
@sebbe1, can you try to use default Android API such as `removeView`?

**Comment by sebschaef** [comment]
No possibility to try it anymore, sorry. But I'm sure it'll work that way then :) Thank you!
