### ISSUE TITLE
disable flipping programmatically

### ISSUE THREAD

**Issue by MohsenShafiee** [davideas/FlipView#8]
Hi
how to disable and enable flipping programmatically!?
thanks

**Comment by davideas** [comment]
@TheLoyalCruel, indeed, I tried and it is not possible.
I'm already adding this functionality, if there are more improvements that you can suggest I can try to integrate them in the next release.
Thanks!

**Comment by davideas** [comment]
I've committed the changes in dev branch for the moment, I will publish the new version (v1.1.1) soon.
I close this, if there's other. Let me know, thanks.
