### ISSUE TITLE
Demo app crashes only with API 23 while flipping entire layouts only on real devices

### ISSUE THREAD

**Issue by davideas** [davideas/FlipView#9]
Experimented that, only with API 23, only flipping entire layouts, demo app:
- On real devices, is killed with no message and it logs: _"E/OpenGLRenderer: resultIndex is -1, the polygon must be invalid!"_.
- On emulator, doesn't crash but it logs: _"W/OpenGLRenderer: Outline has 0 area, no spot shadow!"_.

If you know why, please let me know.

**Comment by davideas** [comment]
Identified the problem.

It seems setting _elevation_ in the custom layouts, it breaks the flip animation and app process is killed!
For the moment I've removed the custom layout and _elevation_ where it is not necessary.

**Comment by ghost** [comment]
Will this be fixed in the near future, or should I just adjust the design to be flat?
